var covid = {
    line_colours:{"leaf":"#ACACAC","zoomable":"#E81D64","zoomable2":"#FBA5C2","search_results":"#119EB9"},
    panel_colours:{"background":"#B0DFE8","label_background":"#097996","value_text":"#005472"},
    area_colours:{"deaths":"#FCE700","recovered":"#757575","remainder":"#E3E3E3"},
    top_label_count: 3,
    previous_data: [],
    previous_type: "",
    current_data:[],
    search_results: false,
    states: {
        "WA": "Washington",
        "CA": "California",
        "MA": "Massachusetts",
        "GA": "Georgia",
        "TX": "Texas",
        "NJ": "New Jersey",
        "CO": "Colorado",
        "IL": "Illinois",
        "PA": "Pennsylvania",
        "VA": "Virginia",
        "MD": "Maryland",
        "IA": "Iowa",
        "NC": "North Carolina",
        "AZ": "Arizona",
        "IN": "Indiana",
        "WI": "Wisconsin",
        "OH": "Ohio",
        "UT": "Utah",
        "DC": "District of Columbia",
        "FL": "Florida",
        "KY": "Kentucky",
        "SC": "South Carolina",
        "TN": "Tennessee",
        "OR": "Oregon",
        "MO": "Missouri",
        "NY": "New York",
        "NH": "New Hampshire",
        "HI": "Hawaii",
        "OK": "Oklahoma",
        "RI": "Rhode Island",
        "NE": "Nebraska",
        "NV": "Nevada",
        "CT": "Connecticut",
        "MN": "Minnesota",
        "KS": "Kansas",
        "LA": "Louisiana",
        "VT": "Vermont",
        "SD": "South Dakota",
        "NM": "New Mexico",
        "MI": "Michigan",
        "DE": "Delaware"
    }

};
